In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df_police = pd.read_csv('Police_Data.csv')
df_police.head()

,ID Reference Number,Subject's race,Subject's gender,Subject's age,Ethnicity,District of occurrence,Adjacent to School,Assigned Division,Assigned Bureau,Event Date/Time
0,1,Asian,Male,43,NON-HISPANIC,6.0,0,TOD,FSB,1/1/2021 1:07
1,2,Black/African American,Male,23,NON-HISPANIC,1.0,0,RCPD,NaN,1/1/2021 0:52
2,3,Black/African American,Male,18,NON-HISPANIC,1.0,0,RCPD,NaN,1/1/2021 0:52
3,4,Black/African American,Male,21,NON-HISPANIC,1.0,0,RCPD,NaN,1/1/2021 0:52
4,5,White,Female,38,HISPANIC,4.0,0,TOD,FSB,1/1/2021 3:00

In [5]:
df_police=df_police.rename(columns={"Subject's race":"Race", "Subject's gender": "Gender", "Subject's age": "Age", "District of occurrence": "District"})
df_police

,ID Reference Number,Race,Gender,Age,Ethnicity,District,Adjacent to School,Assigned Division,Assigned Bureau,Event Date/Time
0,1,Asian,Male,43,NON-HISPANIC,6.0,0,TOD,FSB,1/1/2021 1:07
1,2,Black/African American,Male,23,NON-HISPANIC,1.0,0,RCPD,NaN,1/1/2021 0:52
2,3,Black/African American,Male,18,NON-HISPANIC,1.0,0,RCPD,NaN,1/1/2021 0:52
3,4,Black/African American,Male,21,NON-HISPANIC,1.0,0,RCPD,NaN,1/1/2021 0:52
4,5,White,Female,38,HISPANIC,4.0,0,TOD,FSB,1/1/2021 3:00
...,...,...,...,...,...,...,...,...,...,...
23505,23506,Black/African American,Male,30,NON-HISPANIC,3.0,0,3D,PSB,6/30/2024 11:00
23506,23507,Asian,Male,60,NON-HISPANIC,3.0,0,3D,PSB,7/1/2024 7:27
23507,23508,White,Male,22,HISPANIC,4.0,0,2D,PSB,6/29/2024 2:42
23508,23509,White,Male,25,HISPANIC,4.0,0,2D,PSB,6/29/2024 2:42
23509,23510,Black/African American,Male,24,NON-HISPANIC,3.0,0,3D,PSB,7/1/2024 16:23